version: '3.3'

services:
  #service 1: definition of mysql database
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=solvefinity
      - MYSQL_USER=solvefinity
    ports:
      - "3306:3306"
    restart: always

  #service 2: definition of phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: php-my-admin
    ports:
      - "8082:80"
    restart: always

    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

#  #service 3: definition of spring-boot app
#  solvefinity:                      # it is just a name, which will be used only in this file.
#    image: solvefinity              # name of the image after dockerfile executes
#    container_name: solvefinity-app # name of the container created from docker image
#    build:
#      context: .                    # docker file path (. means root directory)
#      dockerfile: Dockerfile        # docker file name
#    ports:
#      - "8084:8084"                 # docker container port with your os port
#    restart: always
#
#    depends_on:                     # define dependencies of this app
#      - db                          # dependency name
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/db_solvefinity?createDatabaseIfNotExist=true
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root